# .prettierrc or .prettierrc.yaml
trailingComma: "es5"
useTabs: false
tabWidth: 4
semi: true
bracketSpacing: true
singleQuote: false
jsxSingleQuote: false
quoteProps: "as-needed"
arrowParens: "always"
endOfLine: "crlf"
